### ISSUE TITLE
Python trace from console

### ISSUE THREAD

**Issue by ghost** [switchdoclabs/SDL_Pi_Weather_80422#1]
pi@raspberrypi:~/wp/SDL_Pi_Weather_80422 $ sudo ./SDL_Pi_Weather_80422.py
./SDL_Pi_Weather_80422.py: 15: ./SDL_Pi_Weather_80422.py: import: not found
./SDL_Pi_Weather_80422.py: 16: ./SDL_Pi_Weather_80422.py: import: not found
./SDL_Pi_Weather_80422.py: 18: ./SDL_Pi_Weather_80422.py: Syntax error: word unexpected (expecting ")")
pi@raspberrypi:~/wp/SDL_Pi_Weather_80422 $ 

pi@raspberrypi:~/wp/SDL_Pi_Weather_80422 $ sudo ./SDL_Pi_Weather_80422Test.py
Traceback (most recent call last):
  File "./SDL_Pi_Weather_80422Test.py", line 39, in <module>
    weatherStation = SDL_Pi_Weather_80422.SDL_Pi_Weather_80422(anenometerPin, rainPin, 0,0, SDL_MODE_I2C_ADS1015)
  File "/home/pi/wp/SDL_Pi_Weather_80422/SDL_Pi_Weather_80422.py", line 179, in **init**
    self.ads1015 = ADS1x15(ic=ADS1015, address=0x48)
  File "./Adafruit_ADS1x15/Adafruit_ADS1x15.py", line 138, in **init**
    self.i2c = Adafruit_I2C(address)
  File "./Adafruit_ADS1x15/Adafruit_I2C.py", line 43, in **init**
    self.bus = smbus.SMBus(busnum if busnum >= 0 else Adafruit_I2C.getPiI2CBusNumber())
IOError: [Errno 2] No such file or directory

**Comment by ltdenard** [comment]
Hey i'm in no way affiliated with switchdoc but I think you may be having the same issue I was having here: https://github.com/switchdoclabs/RaspberryPi-WeatherPiArduinoV2/issues/2#issuecomment-224438068

If you have the weatherrack, it requires the Adafruit ADS1115 device which is what it is looking for at the 0x48 address. Refer to my issue for pin wiring and code changes to read the instruments after you have the module.
